id: docker
label: Docker
available: true
trustLevel: "stable"
job:
  features:
    - type: DOCKER_INFO
      label: Docker image
      mandatory: true
      defaultValue: hello-world
    - type: SCHEDULER
      label: Scheduled
      mandatory: true

      