context:
  id: docker
  label: Docker
  available: true
  trustLevel: "official"
  features:
    - field: DOCKER_INFO
      label: Docker image
      isMandatory: true
      defaultValue: hello-world
    - field: SCHEDULER
      label: Scheduled
      isMandatory: true

techno:
  id: generic
  label: Generic
  available: true
  icon: docker
